export const IDEA_PROPOSAL_QUESTIONS = [
  { key: "problem", label: "1. What problem are you solving?" },
  { key: "whoExperiences", label: "2. Who experiences this problem?" },
  { key: "problemImportance", label: "3. Why is this problem important to solve now?" },
  { key: "currentSolutions", label: "4. How are people solving it today?" },
  { key: "ideaName", label: "5. Project/Company name?" },
  { key: "ideaDescription", label: "6. What is your idea/solution in simple words?" },
  { key: "valueProposition", label: "7. What is the unique benefit/value proposition?" },
  { key: "idealCustomer", label: "8. Who is your ideal customer?" },
  { key: "targetMarket", label: "9. What market/industry does your solution target?" },
  { key: "marketSize", label: "10. How large is your potential market?" },
  { key: "customerReach", label: "11. Where or how will you reach your customers?" },
  { key: "hasCustomers", label: "12. Do you already have customers/users?" },
  { key: "customerCount", label: "13. How many customers/users do you currently have?" },
  { key: "hasRevenue", label: "14. Do you already generate revenue?" },
  { key: "revenueAmount", label: "15. How much revenue so far?" },
  { key: "revenueRecurring", label: "16. Is revenue recurring or one-time?" },
  { key: "productUsage", label: "17. Do customers actively use the product?" },
  { key: "monetization", label: "18. How will you make money?" },
  { key: "pricing", label: "19. What do you plan to charge?" },
  { key: "mainCosts", label: "20. What are your main costs?" },
  { key: "successIn12Months", label: "21. What does success look like in 12 months?" },
  { key: "directCompetitors", label: "22. Who are your direct competitors?" },
  { key: "competitorStrengths", label: "23. What do competitors do well?" },
  { key: "competitorWeakness", label: "24. Where can you outperform them?" },
  { key: "currentStage", label: "25. What stage are you currently in?" },
  { key: "hasDemo", label: "26. Do you have a demo/prototype?" },
  { key: "existingFeatures", label: "27. Which key features already exist?" },
  { key: "featuresToBuild", label: "28. Which features still need to be built?" },
  { key: "foundedBefore", label: "29. Have you founded or launched a startup before?" },
  { key: "soloOrCoFounders", label: "30. Solo or with co-founders?" },
  { key: "personalSkills", label: "31. What skills do you personally bring?" },
  { key: "missingSkills", label: "32. What skills are missing from your team?" },
  { key: "timePerWeek", label: "33. How much time per week can you dedicate?" },
  { key: "personalInvestment", label: "34. Have you invested personal money?" },
  { key: "externalFunding", label: "35. Have you received any external funding?" },
  { key: "fundingNeeded", label: "36. How much funding do you think you need now?" },
  { key: "fundingUseCase", label: "37. What would funding be used for?" },
  { key: "investorType", label: "38. What type of investors are you looking for?" },
  { key: "nextSteps", label: "39. What are the next 3 steps you plan to take?" },
  { key: "currentObstacle", label: "40. What is your biggest current obstacle?" },
  { key: "mentorHelp", label: "41. What help do you need from mentors?" },
  { key: "technicalExpertHelp", label: "42. What help do you need from technical experts?" }
] as const;
